#spring:
#  kafka:
#   consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeSerializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
#      group-id: library-events-listener-group
#      properties:
#        acks: all
#        retries: 10
#       
#   admin:
#      properties:
#        bootstrap-servers: localhost:9092,localhost9093,localhost=9094#  profiles:#    active:#    - local
#server:
#  port: 8001      
  
#server:
#  port: 9000
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers:
#      - localhost:9092
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers:
#      - localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer 